/**
 * Runs the golden fixture corpus (`contracts/fixtures/*.json`, generated by
 * `contracts/fixtures/generate_fixtures.py` from the real Pydantic models) through this
 * package's Zod port and asserts byte-identical valid output and identical error messages, per
 * `docs/typescript-rewrite.md`'s "Contract preservation strategy". This is the single most
 * important test in this package: it is what makes "the Zod schemas match the Pydantic contract"
 * a checkable fact instead of a vibe.
 */

import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import type { z } from "zod";
import { DomainError } from "./errors.js";
import {
  PixelArtSourceSchema,
  PixelDefinitionSchema,
  PixelEditSchema,
  PixelEditsSchema,
  PixelLayerSchema,
  PixelPoseSchema,
  applyPixelEdits,
} from "./authoring.js";
import { PixelDrawingSchema } from "./drawing.js";
import {
  AssetClipSchema,
  AssetSpecSchema,
  RenderOptionsSchema,
  RenderStateSchema,
  type AssetSpec,
} from "./models.js";
import {
  assetLayouts,
  clipDurationMs,
  clipPlayback,
  getAssetProfile,
  normalizeAsset,
  resolveAsset,
} from "./assets.js";

interface PydanticIssue {
  msg: string;
  loc: (string | number)[];
  type: string;
}

interface SchemaCase {
  name: string;
  status: "valid" | "invalid";
  input: unknown;
  output?: unknown;
  errors?: PydanticIssue[];
}

function fixturesDir(): string {
  return fileURLToPath(new URL("../../../contracts/fixtures/", import.meta.url));
}

function loadFixture<Case>(filename: string): Case[] {
  const path = fixturesDir() + filename;
  const parsed = JSON.parse(readFileSync(path, "utf-8")) as { cases: Case[] };
  return parsed.cases;
}

/** Rebuilds pydantic's `{msg, loc, type}` shape from a ZodError, using the `pydanticType` tag
 * every issue in this package's schemas is required to carry (see `errors.ts`'s `modelObject`/
 * `addPydanticIssue`). Falls back to the raw Zod issue code if a tag is somehow missing, so a
 * gap is visible in a failing assertion rather than silently masked. */
function normalizeZodError(error: z.ZodError): PydanticIssue[] {
  return error.issues.map((issue) => {
    const params = (issue as unknown as { params?: { pydanticType?: string } }).params;
    return {
      msg: issue.message,
      loc: issue.path as (string | number)[],
      type: params?.pydanticType ?? issue.code,
    };
  });
}

function runSchemaFixtures(filename: string, schema: z.ZodType): void {
  describe(filename, () => {
    for (const testCase of loadFixture<SchemaCase>(filename)) {
      it(testCase.name, () => {
        const result = schema.safeParse(testCase.input);
        if (testCase.status === "valid") {
          if (!result.success) {
            throw new Error(`expected valid, got errors: ${JSON.stringify(result.error.issues)}`);
          }
          expect(result.data).toEqual(testCase.output);
        } else {
          if (result.success) {
            throw new Error(`expected invalid, got: ${JSON.stringify(result.data)}`);
          }
          expect(normalizeZodError(result.error)).toEqual(testCase.errors);
        }
      });
    }
  });
}

runSchemaFixtures("pixel-pose.json", PixelPoseSchema);
runSchemaFixtures("pixel-layer.json", PixelLayerSchema);
runSchemaFixtures("pixel-definition.json", PixelDefinitionSchema);
runSchemaFixtures("pixel-drawing.json", PixelDrawingSchema);
runSchemaFixtures("pixel-art-source.json", PixelArtSourceSchema);
runSchemaFixtures("asset-spec.json", AssetSpecSchema);
runSchemaFixtures("render-options.json", RenderOptionsSchema);
runSchemaFixtures("render-state.json", RenderStateSchema);
runSchemaFixtures("asset-clip.json", AssetClipSchema);

describe("pixel-edits.json", () => {
  for (const testCase of loadFixture<SchemaCase>("pixel-edits.json")) {
    it(testCase.name, () => {
      const schema = Array.isArray(testCase.input) ? PixelEditsSchema : PixelEditSchema;
      const result = schema.safeParse(testCase.input);
      if (testCase.status === "valid") {
        if (!result.success) {
          throw new Error(`expected valid, got errors: ${JSON.stringify(result.error.issues)}`);
        }
        expect(result.data).toEqual(testCase.output);
      } else {
        if (result.success) {
          throw new Error(`expected invalid, got: ${JSON.stringify(result.data)}`);
        }
        expect(normalizeZodError(result.error)).toEqual(testCase.errors);
      }
    });
  }
});

interface ApplyEditsCase {
  name: string;
  definition: unknown;
  edits: unknown;
  status: "ok" | "error" | "revalidation_error";
  output?: unknown;
  error?: string;
  errors?: PydanticIssue[];
}

describe("pixel-edits-apply.json", () => {
  for (const testCase of loadFixture<ApplyEditsCase>("pixel-edits-apply.json")) {
    it(testCase.name, () => {
      const definition = PixelDefinitionSchema.parse(testCase.definition);
      const editsResult = PixelEditsSchema.safeParse(testCase.edits);
      if (!editsResult.success) {
        throw new Error(`fixture's edits should themselves be valid: ${testCase.name}`);
      }
      const edits = editsResult.data;

      if (testCase.status === "ok") {
        const result = applyPixelEdits(definition, edits);
        expect(result).toEqual(testCase.output);
        return;
      }
      if (testCase.status === "error") {
        expect(() => applyPixelEdits(definition, edits)).toThrow(testCase.error);
        return;
      }
      // revalidation_error: apply_pixel_edits' final `PixelDefinition.model_validate(data)`
      // itself fails (the resulting document is invalid), so applyPixelEdits should throw a
      // ZodError whose reduced issues match the fixture's.
      try {
        applyPixelEdits(definition, edits);
        throw new Error("expected applyPixelEdits to throw");
      } catch (exc) {
        if (!(exc instanceof Error) || exc.name !== "ZodError") {
          throw exc;
        }
        expect(normalizeZodError(exc as unknown as z.ZodError)).toEqual(testCase.errors);
      }
    });
  }
});

interface SpecFunctionCase {
  name: string;
  input: Record<string, unknown>;
  status: "ok" | "domain_error";
  output?: unknown;
  error?: string;
}

function runSpecFunctionFixtures(
  filename: string,
  fn: (spec: AssetSpec) => unknown,
): void {
  describe(filename, () => {
    for (const testCase of loadFixture<SpecFunctionCase>(filename)) {
      it(testCase.name, () => {
        const spec = AssetSpecSchema.parse(testCase.input);
        if (testCase.status === "ok") {
          expect(fn(spec)).toEqual(testCase.output);
        } else {
          expect(() => fn(spec)).toThrow(DomainError);
          try {
            fn(spec);
          } catch (exc) {
            expect(exc).toBeInstanceOf(DomainError);
            expect((exc as DomainError).message).toBe(testCase.error);
          }
        }
      });
    }
  });
}

runSpecFunctionFixtures("asset-layouts.json", (spec) => assetLayouts(spec));
runSpecFunctionFixtures("resolve-asset.json", (spec) => resolveAsset(spec));
runSpecFunctionFixtures("normalize-asset.json", (spec) => normalizeAsset(spec));

interface AssetProfileCase {
  name: string;
  kind: string;
  preset: string | null;
  status: "ok" | "domain_error";
  output?: unknown;
  error?: string;
}

describe("asset-profile.json", () => {
  for (const testCase of loadFixture<AssetProfileCase>("asset-profile.json")) {
    it(testCase.name, () => {
      if (testCase.status === "ok") {
        expect(getAssetProfile(testCase.kind, testCase.preset)).toEqual(testCase.output);
      } else {
        expect(() => getAssetProfile(testCase.kind, testCase.preset)).toThrow(DomainError);
        try {
          getAssetProfile(testCase.kind, testCase.preset);
        } catch (exc) {
          expect((exc as DomainError).message).toBe(testCase.error);
        }
      }
    });
  }
});

interface ClipPlaybackCase {
  name: string;
  kind: string;
  clip_name: string;
  clip: unknown;
  playback: number[];
  duration_ms: number;
}

describe("clip-playback.json", () => {
  for (const testCase of loadFixture<ClipPlaybackCase>("clip-playback.json")) {
    it(testCase.name, () => {
      const clip = AssetClipSchema.parse(testCase.clip);
      expect(clipPlayback(testCase.kind, testCase.clip_name, clip)).toEqual(testCase.playback);
      expect(clipDurationMs(testCase.kind, testCase.clip_name)).toBe(testCase.duration_ms);
    });
  }
});
