"""Four native chair views: a top-down 3/4 look (dominant cushion-top surface,
thin legs peeking below), matching pixel-agents' own CUSHIONED_CHAIR reference art
instead of a flat front elevation."""

from pixel_art_mcp.pixel_art import Canvas, PixelArt

art = PixelArt(
    {"D": "#263b3b", "W": "#946143", "H": "#d5a66d", "C": "#4f9c85", "T": "#94ceb0"},
    {a: (16, 32) for a in (0, 90, 180, 270)},
)
ROWS = {
    0: [
        "...CCCCCCCCCC...",
        "...CCCCCCCCCC...",
        "..CTTTTTTTTTTC..",
        "..CTTTTTTTTTTC..",
        "..DTTTTTTTTTTD..",
        "..DTTTTTTTTTTD..",
        "..DCCCCCCCCCCD..",
        "..DCCCCCCCCCCD..",
        "..DCCCCCCCCCCD..",
        "..DCCCCCCCCCCD..",
        "..DCCCCCCCCCCD..",
        "..DCCCCCCCCCCD..",
        "..DCDDDDDDDDCD..",
        "..DCDDDDDDDDCD..",
        "..CTTTTTTTTTTC..",
        "..CTTTTTTTTTTC..",
        "..CTTTTTTTTTTC..",
        "..CTTTTTTTTTTC..",
        "..CTTTTTTTTTTC..",
        "..CTTTTTTTTTTC..",
        "..CTTTTTTTTTTC..",
        "..CTTTTTTTTTTC..",
        "..DCCCCCCCCCCD..",
        "..DCCCCCCCCCCD..",
        "..DCCCCCCCCCCD..",
        "..DCCCCCCCCCCD..",
        "..DDDDDDDDDDDD..",
        "..DDDDDDDDDDDD..",
        "..DWD......DWD..",
        "..DWD......DWD..",
        "..DDD......DDD..",
        "..DDD......DDD..",
    ],
    90: [
        ".TT.............",
        ".TT.............",
        "TCCT............",
        "TCCT............",
        "TCCT............",
        "TCCT............",
        "TCCT............",
        "TCCT............",
        "TCCTTTTTTTT.....",
        "TCCTTTTTTTT.....",
        "TCCTCCCCCCCT....",
        "TCCTCCCCCCCT....",
        "TCCTCCCCCCCT....",
        "TCCTCCCCCCCT....",
        "TCCTCCCCCCCT....",
        "TCCTCCCCCCCT....",
        "DTCDCCCCCCCT....",
        "DTCDCCCCCCCT....",
        "DTTDCCCCCCCT....",
        "DTTDCCCCCCCT....",
        "DTTTCCCCCCCT....",
        "DTTTCCCCCCCT....",
        "DTTTTTTTTTCT....",
        "DTTTTTTTTTCT....",
        "DTTTTTTTTTTD....",
        "DTTTTTTTTTTD....",
        "DDDDDDDDDDDD....",
        "DDDDDDDDDDDD....",
        "DWWD....DWWD....",
        "DWWD....DWWD....",
        "DDDD....DDDD....",
        "DDDD....DDDD....",
    ],
    180: [
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "................",
        "...CCCCCCCCCC...",
        "...CCCCCCCCCC...",
        "..CTTTTTTTTTTC..",
        "..CTTTTTTTTTTC..",
        "..DTTTTTTTTTTD..",
        "..DTTTTTTTTTTD..",
        "..DCCCCCCCCCCD..",
        "..DCCCCCCCCCCD..",
        "..DCCCCCCCCCCD..",
        "..DCCCCCCCCCCD..",
        "..DCCCCCCCCCCD..",
        "..DCCCCCCCCCCD..",
        "..DCCCCCCCCCCD..",
        "..DCCCCCCCCCCD..",
        "..DCCCCCCCCCCD..",
        "..DCCCCCCCCCCD..",
        "..DCCCCCCCCCCD..",
        "..DCCCCCCCCCCD..",
        "..DDDDDDDDDDDD..",
        "..DDDDDDDDDDDD..",
        "..DWD......DWD..",
        "..DWD......DWD..",
        "..DDD......DDD..",
        "..DDD......DDD..",
    ],
    270: [
        ".............TT.",
        ".............TT.",
        "............TCCT",
        "............TCCT",
        "............TCCT",
        "............TCCT",
        "............TCCT",
        "............TCCT",
        ".....TTTTTTTTCCT",
        ".....TTTTTTTTCCT",
        "....TCCCCCCCTCCT",
        "....TCCCCCCCTCCT",
        "....TCCCCCCCTCCT",
        "....TCCCCCCCTCCT",
        "....TCCCCCCCTCCT",
        "....TCCCCCCCTCCT",
        "....TCCCCCCCDCTD",
        "....TCCCCCCCDCTD",
        "....TCCCCCCCDTTD",
        "....TCCCCCCCDTTD",
        "....TCCCCCCCTTTD",
        "....TCCCCCCCTTTD",
        "....TCTTTTTTTTTD",
        "....TCTTTTTTTTTD",
        "....DTTTTTTTTTTD",
        "....DTTTTTTTTTTD",
        "....DDDDDDDDDDDD",
        "....DDDDDDDDDDDD",
        "....DWWD....DWWD",
        "....DWWD....DWWD",
        "....DDDD....DDDD",
        "....DDDD....DDDD",
    ],
}
for angle, rows in ROWS.items():
    art.layer("body", angle, Canvas.from_rows(rows))
art.save(scene)
