import { Canvas, PixelArt } from "@pixel-art-mcp/pixel-core";

/**
 * Four native chair views: a top-down 3/4 look (dominant cushion-top surface, thin legs peeking
 * below), matching pixel-agents' own CUSHIONED_CHAIR reference art instead of a flat front
 * elevation.
 *
 * Ported from `chair.py`. `modify_chair.ts` edits the "body" layer this script saves, so its
 * layer name and per-angle patch shapes must stay exactly as authored here.
 */
export default function main(scene: Scene): void {
  const art = new PixelArt(
    { D: "#263b3b", W: "#946143", H: "#d5a66d", C: "#4f9c85", T: "#94ceb0" },
    { 0: [16, 32], 90: [16, 32], 180: [16, 32], 270: [16, 32] },
  );
  const ROWS: Record<0 | 90 | 180 | 270, readonly string[]> = {
    0: [
      "...CCCCCCCCCC...",
      "...CCCCCCCCCC...",
      "..CTTTTTTTTTTC..",
      "..CTTTTTTTTTTC..",
      "..DTTTTTTTTTTD..",
      "..DTTTTTTTTTTD..",
      "..DCCCCCCCCCCD..",
      "..DCCCCCCCCCCD..",
      "..DCCCCCCCCCCD..",
      "..DCCCCCCCCCCD..",
      "..DCCCCCCCCCCD..",
      "..DCCCCCCCCCCD..",
      "..DCDDDDDDDDCD..",
      "..DCDDDDDDDDCD..",
      "..CTTTTTTTTTTC..",
      "..CTTTTTTTTTTC..",
      "..CTTTTTTTTTTC..",
      "..CTTTTTTTTTTC..",
      "..CTTTTTTTTTTC..",
      "..CTTTTTTTTTTC..",
      "..CTTTTTTTTTTC..",
      "..CTTTTTTTTTTC..",
      "..DCCCCCCCCCCD..",
      "..DCCCCCCCCCCD..",
      "..DCCCCCCCCCCD..",
      "..DCCCCCCCCCCD..",
      "..DDDDDDDDDDDD..",
      "..DDDDDDDDDDDD..",
      "..DWD......DWD..",
      "..DWD......DWD..",
      "..DDD......DDD..",
      "..DDD......DDD..",
    ],
    90: [
      ".TT.............",
      ".TT.............",
      "TCCT............",
      "TCCT............",
      "TCCT............",
      "TCCT............",
      "TCCT............",
      "TCCT............",
      "TCCTTTTTTTT.....",
      "TCCTTTTTTTT.....",
      "TCCTCCCCCCCT....",
      "TCCTCCCCCCCT....",
      "TCCTCCCCCCCT....",
      "TCCTCCCCCCCT....",
      "TCCTCCCCCCCT....",
      "TCCTCCCCCCCT....",
      "DTCDCCCCCCCT....",
      "DTCDCCCCCCCT....",
      "DTTDCCCCCCCT....",
      "DTTDCCCCCCCT....",
      "DTTTCCCCCCCT....",
      "DTTTCCCCCCCT....",
      "DTTTTTTTTTCT....",
      "DTTTTTTTTTCT....",
      "DTTTTTTTTTTD....",
      "DTTTTTTTTTTD....",
      "DDDDDDDDDDDD....",
      "DDDDDDDDDDDD....",
      "DWWD....DWWD....",
      "DWWD....DWWD....",
      "DDDD....DDDD....",
      "DDDD....DDDD....",
    ],
    180: [
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "................",
      "...CCCCCCCCCC...",
      "...CCCCCCCCCC...",
      "..CTTTTTTTTTTC..",
      "..CTTTTTTTTTTC..",
      "..DTTTTTTTTTTD..",
      "..DTTTTTTTTTTD..",
      "..DCCCCCCCCCCD..",
      "..DCCCCCCCCCCD..",
      "..DCCCCCCCCCCD..",
      "..DCCCCCCCCCCD..",
      "..DCCCCCCCCCCD..",
      "..DCCCCCCCCCCD..",
      "..DCCCCCCCCCCD..",
      "..DCCCCCCCCCCD..",
      "..DCCCCCCCCCCD..",
      "..DCCCCCCCCCCD..",
      "..DCCCCCCCCCCD..",
      "..DCCCCCCCCCCD..",
      "..DDDDDDDDDDDD..",
      "..DDDDDDDDDDDD..",
      "..DWD......DWD..",
      "..DWD......DWD..",
      "..DDD......DDD..",
      "..DDD......DDD..",
    ],
    270: [
      ".............TT.",
      ".............TT.",
      "............TCCT",
      "............TCCT",
      "............TCCT",
      "............TCCT",
      "............TCCT",
      "............TCCT",
      ".....TTTTTTTTCCT",
      ".....TTTTTTTTCCT",
      "....TCCCCCCCTCCT",
      "....TCCCCCCCTCCT",
      "....TCCCCCCCTCCT",
      "....TCCCCCCCTCCT",
      "....TCCCCCCCTCCT",
      "....TCCCCCCCTCCT",
      "....TCCCCCCCDCTD",
      "....TCCCCCCCDCTD",
      "....TCCCCCCCDTTD",
      "....TCCCCCCCDTTD",
      "....TCCCCCCCTTTD",
      "....TCCCCCCCTTTD",
      "....TCTTTTTTTTTD",
      "....TCTTTTTTTTTD",
      "....DTTTTTTTTTTD",
      "....DTTTTTTTTTTD",
      "....DDDDDDDDDDDD",
      "....DDDDDDDDDDDD",
      "....DWWD....DWWD",
      "....DWWD....DWWD",
      "....DDDD....DDDD",
      "....DDDD....DDDD",
    ],
  };
  for (const angle of [0, 90, 180, 270] as const) {
    art.layer("body", angle, Canvas.fromRows(ROWS[angle]));
  }
  art.save(scene);
}
